; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
monitor_filters = esp32_exception_decoder


; Flash size (N8 = 8MB)
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv

; IMPORTANT for ESP32-S3 OPI PSRAM modules
board_build.arduino.memory_type = qio_opi

lib_deps =
  zinggjm/GxEPD2 @ ^1.6.4
  adafruit/Adafruit GFX Library @ ^1.11.9
  sensirion/Sensirion I2C SEN5X @ ^0.3.0
  h2zero/NimBLE-Arduino@^1.4.2

build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_CDC_ON_BOOT=1
  
  
